// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9NszV40pE8vYcTMkvMKz2z7ZupILwJSI',
    appId: '1:848047799414:web:7269daa33f78f9bf9b7357',
    messagingSenderId: '848047799414',
    projectId: 'unicourse-95fad',
    authDomain: 'unicourse-95fad.firebaseapp.com',
    storageBucket: 'unicourse-95fad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCz4PUl58mOzTxWwADBxyOwHfLCDhj0cM',
    appId: '1:848047799414:android:5ac37779cddb681e9b7357',
    messagingSenderId: '848047799414',
    projectId: 'unicourse-95fad',
    storageBucket: 'unicourse-95fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwZMmBtC7_kMigw4flFMXSHNveYwfDwSg',
    appId: '1:848047799414:ios:df33ff4c94ae27d89b7357',
    messagingSenderId: '848047799414',
    projectId: 'unicourse-95fad',
    storageBucket: 'unicourse-95fad.appspot.com',
    iosBundleId: 'com.example.uniCourse',
  );
}
